In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pickle

In [2]:
data = pd.read_csv("Forest_fire.csv")

In [3]:
X = data.drop(['Area','Fire Occurrence'],axis='columns')
X = np.array(X)
print(X)

[[ 40  45  20]
 [ 50  30  10]
 [ 10  20  70]
 [ 60  45  70]
 [ 30  48  10]
 [ 50  15  30]
 [  5  35  35]
 [  5  20  70]
 [ 60  32  19]
 [ 30  50  45]
 [ 40  55  80]
 [ 30  39 100]
 [ 10  12  12]
 [ 20  23  23]
 [ 60  34  15]
 [ 80   4  68]
 [ 25  56  79]
 [ 12  45  90]
 [ 28  43  15]
 [ 26   0  32]
 [ 32  37  21]
 [ 45  48  12]
 [ 56  15  65]
 [ 67  45  33]
 [ 78  49   8]
 [ 89  45  18]
 [ 21  12  44]
 [ 11  20  59]
 [  1  32  70]
 [  5  20  45]
 [ 42  43  20]
 [ 32  60  30]
 [  5  15   5]
 [ 20  30   5]
 [ 30  51   2]
 [ 60  60  10]
 [ 10  10  60]
 [  0  30   0]
 [ 45  45  15]]


In [4]:
y = data.drop(['Area','Oxygen','Temperature','Humidity'],axis='columns')
y = np.array(y)
y = y.transpose()[0]
print(y)

[1 1 0 1 1 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0
 0 1]


In [5]:
model = LogisticRegression()

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3)

In [7]:
model.fit(X_train, y_train)

LogisticRegression()

In [8]:
model.score(X_test, y_test)

1.0

In [9]:
final=[np.array([45,20,20])]

b = model.predict_proba(final)
print(b)

[[0.96381694 0.03618306]]


In [10]:
pickle.dump(model,open('model.pkl','wb'))